name: Do things
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  DoTheThing:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Doing the thing"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'

      - name: Install dependencies
        run: |
          go get .

      - name: Build
        run: go build -v

      - name: Test
        run : go test
        
      - name: List
        run: |
          echo "Looking at ${{ github.repository }}"
          tree
               
